server:
  port: ${NEXTCLOUD_DLNA_SERVER_PORT:8080}
  interface: ${NEXTCLOUD_DLNA_INTERFACE:eth0}
  friendlyName: ${NEXTCLOUD_DLNA_FRIENDLY_NAME:Nextcloud-DLNA}

nextcloud:
  filesDir: ${NEXTCLOUD_DATA_DIR}
  db:
    type: ${NEXTCLOUD_DB_TYPE:mariadb}
    host: ${NEXTCLOUD_DB_HOST:localhost}
    port: ${NEXTCLOUD_DB_PORT:3306}
    name: ${NEXTCLOUD_DB_NAME:nextcloud}
    user: ${NEXTCLOUD_DB_USER:nextcloud}
    pass: ${NEXTCLOUD_DB_PASS:nextcloud}

spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

