server:
  port: ${NEXTCLOUD_DLNA_SERVER_PORT:8080}
  interface: ${NEXTCLOUD_DLNA_INTERFACE:eth0}
  friendlyName: ${NEXTCLOUD_DLNA_FRIENDLY_NAME:Nextcloud-DLNA}

nextcloud:
  filesDir: ${NEXTCLOUD_DATA_DIR}

spring:
  datasource:
    url: "jdbc:mariadb://${NEXTCLOUD_DB_HOST:localhost}:${NEXTCLOUD_DB_PORT:3306}/${NEXTCLOUD_DB_NAME:nextcloud}"
    username: ${NEXTCLOUD_DB_USER:nextcloud}
    password: ${NEXTCLOUD_DB_PASS:nextcloud}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

